export const path = {
  HOME: "/*",
  HOME__PAGE: ":page",
  LOGIN: "dang-nhap-tai-khoan",
  SIGNUP: "dang-ky-tai-khoan",
  CHO_THUE_CAN_HO: "cho-thue-can-ho",
  CHO_THUE_MAT_BANG: "cho-thue-mat-bang",
  NHA_CHO_THUE: "nha-cho-thue",
  CHO_THUE_PHONG_TRO: "cho-thue-phong-tro",
  CHI_TIET__TITLE__POSTID: "chi-tiet/:title/:postId",
  TIM_KIEM: "tim-kiem",
  LIEN_HE: "lien-he",
  QUAN_LY: "/quan-ly/*",
  DANG_TIN_MOI: "dang-tin-moi",
  QUAN_LY_TIN_DANG: "quan-ly-tin-dang",
  SUA_THONG_TIN_CA_NHAN: "sua-thong-tin-ca-nhan",
};
